### ISSUE TITLE
Zenodo entry

### ISSUE THREAD

**Issue by moble** [cjhaster/NRSurrogateCatalog#11]
I can't tell who submitted [the zenodo record](https://zenodo.org/record/8115310), but I figured this might be as good a place as any to suggest this: That record needs at least a *little* more detail in the description.  It says, "Refer to the paper for more details. "  But what paper?  There should at least be a link to the arxiv version.

**Comment by cjhaster** [comment]
Hi Mike,

That is indeed the plan, and the paper will appear in a linkable form shortly. We had the data release ready to go, and thought it would be convenient to put it up on Zenodo now (so we had the final Zenodo DOI to put in the paper and so on). 
So for now the data are final, but their presentation will "remain preliminary" until the accompanying paper is made public as well.

Thanks for checking up on this though!
