### ISSUE TITLE
pesummary compatible?

### ISSUE THREAD

**Issue by sfield17** [cjhaster/NRSurrogateCatalog#7]
Are the public posteriors compatible with pesummary (in addition to the custom nr-catalog package?)

**Comment by avivajpeyi** [comment]
This is a great idea! I think @tousifislam was working on making PESummary-compatible posterior result files (with the kick posteriors)? Are these on CIT?

**Comment by avivajpeyi** [comment]
@tousifislam  has converted the files to be PESummary compatible
